.TH HTTPOSMS-SERVER 1 httposms-server\-VERSION
.SH NAME
httposms-server \- HTTP tunnel over SMS server
.SH SYNOPSIS
.B httposms-server
.RB [ \-v ]
.SH DESCRIPTION

Placeholder, to be written

.SH OPTIONS
.TP
.B \-v
Placeholder, to be written
.SH BUGS
Send all bug reports https://github.com/httposms/httposms-server.com

